New upstream version 5.9.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/macsys.lisp"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE build build_cpu build_vendor build_os host host_cpu host_vendor host_os win32 WIN32_TRUE WIN32_FALSE clisp_found cmucl_found sbcl_found acl6_found gcl_found openmcl_found CLISP_TRUE CLISP_FALSE GCL_TRUE GCL_FALSE CMUCL_TRUE CMUCL_FALSE SBCL_TRUE SBCL_FALSE ACL6_TRUE ACL6_FALSE OPENMCL_TRUE OPENMCL_FALSE GCL_ALT_LINK_TRUE GCL_ALT_LINK_FALSE CLISP_NAME CLISP_RUNTIME CLISP_RUNTIME_PATH CMUCL_NAME CMUCL_RUNTIME CMUCL_RUNTIME_PATH SBCL_NAME GCL_NAME ACL6_NAME OPENMCL_NAME DEFAULTLISP WISH POSIX_SHELL expanded_top_srcdir expanded_exec_prefix expanded_libdir expanded_libexecdir expanded_datadir expanded_infodir default_layout_autotools LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot build build_cpu build_vendor build_os host host_cpu host_vendor host_os win32 WIN32_TRUE WIN32_FALSE clisp_found cmucl_found sbcl_found acl6_found gcl_found openmcl_found CLISP_TRUE CLISP_FALSE GCL_TRUE GCL_FALSE CMUCL_TRUE CMUCL_FALSE SBCL_TRUE SBCL_FALSE ACL6_TRUE ACL6_FALSE OPENMCL_TRUE OPENMCL_FALSE GCL_ALT_LINK_TRUE GCL_ALT_LINK_FALSE CLISP_NAME CLISP_RUNTIME CLISP_RUNTIME_PATH CMUCL_NAME CMUCL_RUNTIME CMUCL_RUNTIME_PATH SBCL_NAME GCL_NAME ACL6_NAME OPENMCL_NAME DEFAULTLISP WISH POSIX_SHELL expanded_top_srcdir expanded_exec_prefix expanded_libdir expanded_libexecdir expanded_datadir expanded_infodir default_layout_autotools LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1221,7 +1221,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-am__api_version="1.6"
+am__api_version="1.7"
 ac_aux_dir=
 for ac_dir in $srcdir $srcdir/.. $srcdir/../..; do
   if test -f $ac_dir/install-sh; then
@@ -1465,6 +1465,15 @@ echo "${ECHO_T}no" >&6
   SET_MAKE="MAKE=${MAKE-make}"
 fi
 
+rm -rf .tst 2>/dev/null
+mkdir .tst 2>/dev/null
+if test -d .tst; then
+  am__leading_dot=.
+else
+  am__leading_dot=_
+fi
+rmdir .tst 2>/dev/null
+
  # test to see if srcdir already configured
 if test "`cd $srcdir && pwd`" != "`pwd`" &&
    test -f $srcdir/config.status; then
@@ -1473,9 +1482,19 @@ echo "$as_me: error: source directory already configured; run \"make distclean\"
    { (exit 1); exit 1; }; }
 fi
 
+# test whether we have cygpath
+if test -z "$CYGPATH_W"; then
+  if (cygpath --version) >/dev/null 2>/dev/null; then
+    CYGPATH_W='cygpath -w'
+  else
+    CYGPATH_W=echo
+  fi
+fi
+
+
 # Define the identity of the package.
  PACKAGE=maxima
- VERSION=5.9.1
+ VERSION=5.9.2
 
 
 cat >>confdefs.h <<_ACEOF
@@ -2614,9 +2633,9 @@ fi
 
 if test x"${cmucl}" = xtrue; then
     if test x"${CMUCL_RUNTIME_PATH}" = x"" ; then
-        CMUCL_RUNTIME_PATH=`${CMUCL_NAME} -noinit -nositeinit -quiet -batch -eval '#+cmu19 (progn (setf (search-list "cmuclbin:") (lisp::parse-unix-search-path lisp::*cmucl-lib*)) (enumerate-search-list (s "cmuclbin:lisp") (when (probe-file s) (format t "~A~%" s) (quit)))) #+cmu18 (format t "~a/../bin/lisp~%" common-lisp::*cmucl-lib*)(quit)'`
+        CMUCL_RUNTIME_PATH=`${CMUCL_NAME} -noinit -nositeinit -quiet -batch -eval '#+cmu19 (progn (setf (search-list "cmuclbin:") (append (lisp::parse-unix-search-path lisp::*cmucl-lib*) (mapcar (function (lambda (p) (concatenate (quote string) p "../bin/"))) (lisp::parse-unix-search-path lisp::*cmucl-lib*))))(enumerate-search-list (s "cmuclbin:lisp") (when (probe-file s) (format t "~A~%" s) (quit)))) #+cmu18 (format t "~a/../bin/lisp~%" common-lisp::*cmucl-lib*)(quit)'`
     fi
-    if test -x ${CMUCL_RUNTIME_PATH} ; then
+    if test -x "${CMUCL_RUNTIME_PATH}" ; then
         echo "cmucl runtime is \"${CMUCL_RUNTIME_PATH}\""
     else
 	cmucl_path=`type -p "${CMUCL_NAME}"`
@@ -2624,13 +2643,13 @@ if test x"${cmucl}" = xtrue; then
 	   	CMUCL_RUNTIME_PATH="${cmucl_path}"
 	else
 		{ { echo "$as_me:$LINENO: error: Unable to determine CMUCL runtime path.
-The best guess for CMUCL runtime \"${CMUCL_RUNTIME_PATH}\" is not
+The best guess for CMUCL runtime, \"${CMUCL_RUNTIME_PATH}\", is not
 an executable. Use the argument
    --with-cmucl-runtime=<path>
 to set the actual CMUCL executable. If the CMUCL lisp command is a shell
 script the CMUCL executable is the program exec'd by that shell script." >&5
 echo "$as_me: error: Unable to determine CMUCL runtime path.
-The best guess for CMUCL runtime \"${CMUCL_RUNTIME_PATH}\" is not
+The best guess for CMUCL runtime, \"${CMUCL_RUNTIME_PATH}\", is not
 an executable. Use the argument
    --with-cmucl-runtime=<path>
 to set the actual CMUCL executable. If the CMUCL lisp command is a shell
@@ -2639,6 +2658,48 @@ script the CMUCL executable is the program exec'd by that shell script." >&2;}
 	fi
     fi
     CMUCL_RUNTIME=`basename ${CMUCL_RUNTIME_PATH}`
+
+   result=`"${CMUCL_RUNTIME_PATH}" -quiet -eval '(format t "MAXIMA_CMUCL_TEST_SUCCESS%")(quit)'`
+   retval=$?
+   if test ! x"${retval}" = x"0" ; then
+      { { echo "$as_me:$LINENO: error: unable to run cmucl runtime = \"${CMUCL_RUNTIME_PATH}\".
+Please specify the full path the the cmucl runtime using the
+    --with-cmucl-runtime=<path>
+flag." >&5
+echo "$as_me: error: unable to run cmucl runtime = \"${CMUCL_RUNTIME_PATH}\".
+Please specify the full path the the cmucl runtime using the
+    --with-cmucl-runtime=<path>
+flag." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+   count=`echo "${result}" | grep -c "MAXIMA_CMUCL_TEST_SUCCESS"`
+   if test ! "${count}" = "1" ; then
+      { { echo "$as_me:$LINENO: error: an error occured while checking cmucl runtime" >&5
+echo "$as_me: error: an error occured while checking cmucl runtime" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
+
+if test x"${gcl}" = xtrue; then
+   result=`"${GCL_NAME}" -batch -eval '#+ansi-cl (format t "MAXIMA_GCL_ANSI_TEST_SUCCESS~%") #-ansi-cl (format t "MAXIMA_GCL_ANSI_TEST_FAILURE~%")'`
+   retval=$?
+   if test ! x"${retval}" = x"0" ; then
+      { { echo "$as_me:$LINENO: error: unable to run gcl executable \"${GCL_NAME}\"." >&5
+echo "$as_me: error: unable to run gcl executable \"${GCL_NAME}\"." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+   count=`echo "${result}" | grep -c "MAXIMA_GCL_ANSI_TEST_SUCCESS"`
+   if test ! "${count}" = "1" ; then
+      { { echo "$as_me:$LINENO: error: The gcl executable \"${GCL_NAME}\" was not compiled with
+the --enable-ansi flag, which is required for Maxima.
+The gcl ANSI-CL check returned
+\"${result}\"." >&5
+echo "$as_me: error: The gcl executable \"${GCL_NAME}\" was not compiled with
+the --enable-ansi flag, which is required for Maxima.
+The gcl ANSI-CL check returned
+\"${result}\"." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
 fi
 
 # Check whether --enable-gcl-alt-link or --disable-gcl-alt-link was given.
@@ -2842,7 +2903,7 @@ expanded_infodir="`eval \"prefix=${tmp_prefix};echo ${infodir}\"`"
 default_layout_autotools="true"
 
 
-                                                                                                                                                                                                                                                                                                                                ac_config_files="$ac_config_files Makefile maxima-local xmaxima-local maxima.spec maxima.iss src/Makefile src/maxima src/maxima.bat src/rmaxima src/autoconf-variables.lisp lisp-utils/Makefile tests/Makefile doc/Makefile doc/emaxima/Makefile doc/info/Makefile doc/intromax/Makefile doc/man/Makefile doc/man/maxima.1 doc/share/Makefile interfaces/Makefile interfaces/emacs/Makefile interfaces/emacs/emaxima/Makefile interfaces/emacs/misc/Makefile interfaces/xmaxima/Makefile interfaces/xmaxima/autoconf-variables.tcl interfaces/xmaxima/Tkmaxima/Header.tcl interfaces/xmaxima/win32/Makefile plotting/header.tcl plotting/mgnuplot share/Makefile demo/Makefile plotting/Makefile"
+                                                                                                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile maxima-local xmaxima-local maxima.spec maxima.iss src/Makefile src/maxima src/maxima.bat src/rmaxima src/autoconf-variables.lisp lisp-utils/Makefile tests/Makefile doc/Makefile doc/emaxima/Makefile doc/info/Makefile doc/intromax/Makefile doc/man/Makefile doc/man/maxima.1 doc/share/Makefile interfaces/Makefile interfaces/emacs/Makefile interfaces/emacs/emaxima/Makefile interfaces/emacs/misc/Makefile interfaces/xmaxima/Makefile interfaces/xmaxima/autoconf-variables.tcl interfaces/xmaxima/Tkmaxima/Header.tcl interfaces/xmaxima/msgs/Makefile interfaces/xmaxima/win32/Makefile plotting/msgs/Makefile plotting/header.tcl plotting/mgnuplot share/Makefile demo/Makefile plotting/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3475,7 +3536,9 @@ do
   "interfaces/xmaxima/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/Makefile" ;;
   "interfaces/xmaxima/autoconf-variables.tcl" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/autoconf-variables.tcl" ;;
   "interfaces/xmaxima/Tkmaxima/Header.tcl" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/Tkmaxima/Header.tcl" ;;
+  "interfaces/xmaxima/msgs/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/msgs/Makefile" ;;
   "interfaces/xmaxima/win32/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/win32/Makefile" ;;
+  "plotting/msgs/Makefile" ) CONFIG_FILES="$CONFIG_FILES plotting/msgs/Makefile" ;;
   "plotting/header.tcl" ) CONFIG_FILES="$CONFIG_FILES plotting/header.tcl" ;;
   "plotting/mgnuplot" ) CONFIG_FILES="$CONFIG_FILES plotting/mgnuplot" ;;
   "share/Makefile" ) CONFIG_FILES="$CONFIG_FILES share/Makefile" ;;
@@ -3567,6 +3630,7 @@ s,@LIBS@,$LIBS,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
+s,@CYGPATH_W@,$CYGPATH_W,;t t
 s,@PACKAGE@,$PACKAGE,;t t
 s,@VERSION@,$VERSION,;t t
 s,@ACLOCAL@,$ACLOCAL,;t t
@@ -3581,6 +3645,7 @@ s,@ac_ct_STRIP@,$ac_ct_STRIP,;t t
 s,@INSTALL_STRIP_PROGRAM@,$INSTALL_STRIP_PROGRAM,;t t
 s,@AWK@,$AWK,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
+s,@am__leading_dot@,$am__leading_dot,;t t
 s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
 s,@build_vendor@,$build_vendor,;t t
