5.28.0-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -5,43 +5,30 @@ AC_INIT(src/macsys.lisp)
 dnl If git is available, the version number here is not used.  
 dnl Instead, git is used to derive the version based on the closest
 dnl annotated branch tag.
-AM_INIT_AUTOMAKE(maxima,5.27.0)
-
-dnl See if git exists.  If it does, update VERSION to include a git tag
-AC_CHECK_PROG(git_found, git, true, false)
-if test x"${git_found}" = xtrue; then
-    # Test to see if git describe works (discarding any output).  If
-    # it works, use it.  Otherwise, fall back on the AM_INIT_AUTOMAKE version.
-    if git describe > /dev/null 2>&1; then
-        VERSION="`git describe --dirty`"
-        # When building RPMs, hyphens in the version are not allowed, so
-        # replace them with underscores.
-        VERSION=`echo $VERSION | sed 's;-;_;g'`
-        AC_MSG_RESULT(Sanitized VERSION derived from git is $VERSION)
-    else
-        AC_MSG_RESULT(git describe failed so let VERSION be $VERSION)
-    fi
-else
-    AC_MSG_RESULT(git not present so let VERSION be $VERSION)
-fi
+AM_INIT_AUTOMAKE(maxima,5.28.0)
 
 AM_PATH_LISPDIR
 
 AC_CANONICAL_HOST
+
+dnl Don't use AC_EXEEXT as that requires a C compiler
 case "$host" in
         *mingw*)
                 win32=true
-                mingw=true 
+                mingw=true
+                EXEEXT=.exe
                 ;;
         *cygwin*)
                 win32=true
                 mingw=false
+                EXEEXT=.exe
                 ;;
         *)
                 win32=false
                 mingw=false
+                EXEEXT=
 esac
-AC_SUBST(win32)
+AC_SUBST(EXEEXT)
 AM_CONDITIONAL(WIN32, test x$win32 = xtrue)
 
 explicit_lisp=false
@@ -59,7 +46,7 @@ AC_ARG_ENABLE(clisp,
 	explicit_lisp=true],
 	[clisp=false])
 AC_ARG_WITH(clisp,
-	[  --with-clisp=<prog>         Use clisp executable <prog> (default clisp)],
+	[  --with-clisp=<prog>          Use clisp executable <prog> (default clisp)],
 	[clisp=true
 	explicit_lisp=true
 	if test "$withval" = "yes"; then
@@ -81,6 +68,20 @@ AC_ARG_WITH(clisp-runtime,
 	CLISP_RUNTIME_PATH="$withval"
 	CLISP_RUNTIME=`basename ${CLISP_RUNTIME_PATH}`],
 	[])
+AC_ARG_ENABLE(clisp-exec,
+	[  --enable-clisp-exec          Create a maxima executable image using CLISP.
+                                No check is made if the version of 
+                                CLISP supports executable images],
+	[case "${enableval}" in
+	    yes) clisp_exec=true 
+                 clisp=true 
+                 explicit_lisp=true ;;
+	    no) clisp_exec=false ;;
+	    *) AC_MSG_ERROR(bad value ${enableval} for --enable-clisp-exec) ;;
+         esac
+	 CLISP_EXEC=${clisp_exec}],
+	[clisp_exec=false
+	 CLISP_EXEC=false])
 if test x"${clisp}" = xtrue ; then
 	if test `echo "$CLISP_NAME" | sed 's/\(.\).*/\1/'` = "/" ; then
 		if test -x "$CLISP_NAME" ; then
@@ -94,6 +95,24 @@ if test x"${clisp}" = xtrue ; then
 	if test x"${clisp_found}" = xfalse ; then
 		AC_MSG_WARN(clisp executable ${CLISP_NAME} not found in PATH)
 	fi	   
+fi
+
+
+dnl See if git exists.  If it does, update VERSION to include a git tag
+AC_CHECK_PROG(git_found, git, true, false)
+if test x"${git_found}" = xtrue; then
+    # Test to see if git describe works (discarding any output).  If
+    # it works, use it.  Otherwise, keep existing value of VERSION.
+    # (git describe fails if git is executed in a non-Git directory, e.g.,
+    # an unpacked tarball. Since the exit codes of git describe are undocumented,
+    # we cannot distinguish that from a missing annotated tag.
+    # Play it safe by refusing to change VERSION.)
+    if git describe > /dev/null 2>&1; then
+        VERSION="`git describe --dirty`"
+        # When building RPMs, hyphens in the version are not allowed, so
+        # replace them with underscores.
+        VERSION=`echo $VERSION | sed 's;-;_;g'`
+    fi
 fi
 
 dnl n.b. cmucl_default_name is hardcoded in "with" message
@@ -126,6 +145,20 @@ AC_ARG_WITH(cmucl-runtime,
 	CMUCL_RUNTIME_PATH="$withval"
 	CMUCL_RUNTIME=`basename ${CMUCL_RUNTIME_PATH}`],
 	[])
+AC_ARG_ENABLE(cmucl-exec,
+	[  --enable-cmucl-exec          Create a maxima executable image using CMUCL.
+                                No check is made if the version of 
+                                CMUCL supports executable images],
+	[case "${enableval}" in
+	    yes) cmucl_exec=true
+                 cmucl=true 
+                 explicit_lisp=true ;;
+	    no) cmucl_exec=false ;;
+	    *) AC_MSG_ERROR(bad value ${enableval} for --enable-cmucl-exec) ;;
+         esac
+	 CMUCL_EXEC=${cmucl_exec}],
+	[cmucl_exec=false
+	 CMUCL_EXEC=false])
 if test x"${cmucl}" = xtrue ; then
 	if test `echo "$CMUCL_NAME" | sed 's/\(.\).*/\1/'` = "/" ; then
 		if test -x "$CMUCL_NAME" ; then
@@ -141,18 +174,6 @@ if test x"${cmucl}" = xtrue ; then
 		AC_MSG_WARN(cmucl executable ${CMUCL_NAME} not found in PATH)
 	fi
 fi
-AC_ARG_ENABLE(cmucl-exec,
-	[  --enable-cmucl-exec          Create a maxima executable image.
-                                No check is made if the version of 
-                                CMUCL supports executable images],
-	[case "${enableval}" in
-	    yes) cmucl_exec=true ;;
-	    no) cmucl_exec=false ;;
-	    *) AC_MSG_ERROR(bad value ${enableval} for --enable-cmucl-exec) ;;
-         esac
-	 CMUCL_EXEC=${cmucl_exec}],
-	[cmucl_exec=false
-	 CMUCL_EXEC=false])
 
 dnl n.b. scl_default_name is hardcoded in "with" message
 scl_default_name=scl
@@ -221,7 +242,21 @@ AC_ARG_WITH(sbcl,
 	else
 		SBCL_NAME="$withval"
 	fi],
-	[SBCL_NAME=${sbcl_default_name}])
+	[SBCL_NAME="${sbcl_default_name}"])
+AC_ARG_ENABLE(sbcl-exec,
+	[  --enable-sbcl-exec           Create a maxima executable image using SBCL.
+                                No check is made if the version of 
+                                SBCL supports executable images],
+	[case "${enableval}" in
+	    yes) sbcl_exec=true 
+                 sbcl=true 
+                 explicit_lisp=true ;;
+	    no) sbcl_exec=false ;;
+	    *) AC_MSG_ERROR(bad value ${enableval} for --enable-sbcl-exec) ;;
+         esac
+	 SBCL_EXEC=${sbcl_exec}],
+	[sbcl_exec=false
+	 SBCL_EXEC=false])
 if test x"${sbcl}" = xtrue ; then
 	if test `echo "$SBCL_NAME" | sed 's/\(.\).*/\1/'` = "/" ; then
 		if test -x "$SBCL_NAME" ; then
@@ -230,11 +265,11 @@ if test x"${sbcl}" = xtrue ; then
 			sbcl_found=false
 		fi
 	else
-		AC_CHECK_PROG(sbcl_found,$SBCL_NAME,true,false)
+		AC_CHECK_PROG(sbcl_found,"$SBCL_NAME",true,false)
 	fi
-	AC_CHECK_PROG(sbcl_found,$SBCL_NAME,true,false)
+	AC_CHECK_PROG(sbcl_found,"$SBCL_NAME",true,false)
 	if test x"${sbcl_found}" = xfalse ; then
-		AC_MSG_WARN(sbcl executable ${SBCL_NAME} not found in PATH)
+		AC_MSG_WARN(sbcl executable "${SBCL_NAME}" not found in PATH)
 	fi
 fi
 	
@@ -333,6 +368,21 @@ AC_ARG_WITH(openmcl,
 		OPENMCL_NAME="$withval"
 	fi],
 	[OPENMCL_NAME=${openmcl_default_name}])
+AC_ARG_ENABLE(openmcl-exec,
+	[  --enable-openmcl-exec        Create a maxima executable image using OPENMCL.
+                                No check is made if the version of 
+                                OPENMCL supports executable images],
+	[case "${enableval}" in
+	    yes) openmcl_exec=true
+                 openmcl=true 
+		 explicit_lisp=true;;
+	    no) openmcl_exec=false ;;
+	    *) AC_MSG_ERROR(bad value ${enableval} for --enable-openmcl-exec) ;;
+         esac
+	 OPENMCL_EXEC=${openmcl_exec}],
+	[openmcl_exec=false
+	 OPENMCL_EXEC=false])
+
 dnl Define ccl as an alias (essentially) for openmcl
 AC_ARG_ENABLE(ccl,
 	[  --enable-ccl                 Use CCL (Clozure Common Lisp)],
@@ -353,6 +403,20 @@ AC_ARG_WITH(ccl,
 		OPENMCL_NAME="$withval"
 	fi],
 	[OPENMCL_NAME=${openmcl_default_name}])
+AC_ARG_ENABLE(ccl-exec,
+	[  --enable-ccl-exec            Create a maxima executable image using CCL.
+                                No check is made if the version of 
+                                CCL supports executable images],
+	[case "${enableval}" in
+	    yes) openmcl_exec=true
+                 openmcl=true 
+                 explicit_lisp=true;;
+	    no) openmcl_exec=false ;;
+	    *) AC_MSG_ERROR(bad value ${enableval} for --enable-ccl-exec) ;;
+         esac
+	 OPENMCL_EXEC=${openmcl_exec}],
+	[openmcl_exec=false
+	 OPENMCL_EXEC=false])
 
 if test x"${openmcl}" = xtrue ; then
 	if test `echo "$OPENMCL_NAME" | sed 's/\(.\).*/\1/'` = "/" ; then
@@ -531,6 +595,73 @@ fi
 
 AM_CONDITIONAL(USE_RECODE, test x$use_recode = xtrue)
 
+dnl Optionally build the windows CHM help files
+dnl default to false as requires win32 and Microsoft HTML Help Workshop
+AC_ARG_ENABLE(chm,
+  [  --enable-chm                 Build Windows CHM help files],
+  [case "${enableval}" in
+       		yes) chm=true ;;
+       		no)  chm=false ;;
+		*) AC_MSG_ERROR(bad value ${enableval} for --enable-chm) ;;
+   esac],
+   [chm=false])
+AM_CONDITIONAL(CHM, test x$chm = xtrue)
+dnl hhc is the HTML Help Compiler for CHM documentation
+hhc_default_name=hhc
+AC_ARG_WITH(hhc,
+	[  --with-hhc=<prog>            Use HTML Help Compiler executable <prog> (default hhc)],
+	[hhc=true
+	if test "$withval" = "yes"; then
+		HHC="${hhc_default_name}"
+	else
+		HHC="$withval"
+	fi],
+	[HHC="${hhc_default_name}"])
+
+# check that hhc exists
+if test x$chm = xtrue; then
+  if ! test -x "${HHC}"; then
+    AC_MSG_ERROR(HTML Help Compiler executable "${HHC}" not found)
+  fi
+fi
+
+dnl Optionally build xmaxima.exe under windows
+dnl default to false as additional software
+AC_ARG_ENABLE(xmaxima_exe,
+  [  --enable-xmaxima-exe         Build Windows xmaxima.exe for installer],
+  [case "${enableval}" in
+       		yes) xmaxima_exe=true ;;
+       		no)  xmaxima_exe=false ;;
+		*) AC_MSG_ERROR(bad value ${enableval} for --enable-xmaxima-exe) ;;
+   esac],
+   [xmaxima_exe=false])
+AM_CONDITIONAL(XMAXIMA_EXE, test x$xmaxima_exe = xtrue)
+
+dnl Tools for building xmaxima.exe on windows
+dnl Hard code the filenames for now.  Can over-ride on make command line
+GCCVER=undefined
+if test x${xmaxima_exe} = xtrue ; then
+  GCCVER=`gcc -dumpversion`
+  if  test x${GCCVER} = x3.3.1; then
+    TCLSTUBLIB=-ltclstub84
+  else
+    TCLSTUBLIB=/c/tcl/lib/tclstub85.lib
+  fi
+  dnl http://code.google.com/p/tclkit/ and http://www.tcl.tk/starkits/
+  TCLKITSH=/c/programs/star/tclkitsh-win32.upx.exe
+  TCLKIT_RUNTIME=/c/programs/star/tclkit-win32.upx.exe 
+  SDXKIT=/c/programs/star/sdx.kit
+  IMGKIT=/c/programs/star/img.kit
+fi
+
+AC_SUBST(GCCVER)
+AC_SUBST(TCLSTUBLIB)
+AC_SUBST(TCLKITSH)
+AC_SUBST(TCLKIT_RUNTIME)
+AC_SUBST(SDXKIT)
+AC_SUBST(IMGKIT)
+AM_CONDITIONAL(GCC331, test x${GCCVER} = x3.3.1)
+
 if test x"${explicit_lisp}" = xfalse ; then
 dnl  	AC_CHECK_PROG(clisp_found,${clisp_default_name},true,false)
 dnl  	if test x"${clisp_found}" = xtrue ; then
@@ -598,13 +729,16 @@ dnl  	fi
 fi
 
 AM_CONDITIONAL(CLISP, test x$clisp = xtrue)
+AM_CONDITIONAL(CLISP_EXEC, test x$clisp_exec = xtrue)
 AM_CONDITIONAL(GCL, test x$gcl = xtrue)
 AM_CONDITIONAL(CMUCL, test x$cmucl = xtrue)
 AM_CONDITIONAL(CMUCL_EXEC, test x${cmucl_exec} = xtrue)
 AM_CONDITIONAL(SCL, test x$scl = xtrue)
 AM_CONDITIONAL(SBCL, test x$sbcl = xtrue)
+AM_CONDITIONAL(SBCL_EXEC, test x$sbcl_exec = xtrue)
 AM_CONDITIONAL(ACL, test x$acl = xtrue)
 AM_CONDITIONAL(OPENMCL, test x$openmcl = xtrue)
+AM_CONDITIONAL(OPENMCL_EXEC, test x${openmcl_exec} = xtrue)
 AM_CONDITIONAL(ECL, test x$ecl = xtrue)
 
 if test x"${clisp}" = xtrue; then
@@ -810,6 +944,7 @@ AC_SUBST(ACL_NAME)
 AC_SUBST(OPENMCL_NAME)
 AC_SUBST(ECL_NAME)
 AC_SUBST(DEFAULTLISP)
+AC_SUBST(HHC)
 
 AC_ARG_WITH(posix-shell,
 	[  --with-posix-shell=<path>    Use <shell> for maxima script (default /bin/sh)],
@@ -896,10 +1031,12 @@ AC_SUBST(EGREP)
 # Configure these files and make them executable
 AC_CONFIG_FILES([maxima-local], chmod +x maxima-local)
 AC_CONFIG_FILES([xmaxima-local], chmod +x xmaxima-local)
-AC_CONFIG_FILES([src/share-subdirs.lisp])
+dnl Convert to DOS line ending (using sed because we know it is present)
+AC_CONFIG_FILES([src/maxima.bat], sed -i -e 's/$/\r/' src/maxima.bat)
 
 AC_OUTPUT(Makefile maxima.spec maxima.iss \
-admin/Makefile src/Makefile src/maxima src/maxima.bat src/rmaxima src/autoconf-variables.lisp \
+admin/Makefile src/Makefile src/maxima src/rmaxima src/autoconf-variables.lisp \
+src/share-subdirs.lisp \
 lisp-utils/Makefile tests/Makefile doc/Makefile \
 doc/emaxima/Makefile doc/info/Makefile doc/info/include-maxima.texi \
 doc/info/de/Makefile doc/info/de.utf8/Makefile \
@@ -923,6 +1060,9 @@ if test x"${clisp}" = xtrue ; then
 	echo "clisp enabled. Executable name: \"${CLISP_NAME}\""
 	echo "clisp runtime is \"${CLISP_RUNTIME_PATH}\""
 fi
+if test x"${clisp_exec}" = xtrue ; then
+   echo "clisp executable image enabled for maxima."
+fi
 if test x"${cmucl}" = xtrue ; then
 	echo "CMUCL enabled. Executable name: \"${CMUCL_NAME}\""
 	echo "cmucl runtime is \"${CMUCL_RUNTIME_PATH}\""
@@ -937,6 +1077,9 @@ fi
 if test x"${sbcl}" = xtrue ; then
 	echo "SBCL enabled. Executable name: \"${SBCL_NAME}\""
 fi
+if test x"${sbcl_exec}" = xtrue ; then
+   echo "sbcl executable image enabled for maxima."
+fi
 if test x"${gcl}" = xtrue ; then
 	echo "GCL enabled. Executable name: \"${GCL_NAME}\""
 	if test x"${gcl_alt_link}" = xtrue ; then
@@ -949,9 +1092,48 @@ fi
 if test x"${openmcl}" = xtrue ; then
 	echo "OpenMCL enabled. Executable name: \"${OPENMCL_NAME}\""
 fi
+if test x"${openmcl_exec}" = xtrue ; then
+   echo "OpenMCL executable image enabled for maxima."
+fi
 if test x"${ecl}" = xtrue ; then
 	echo "ECL enabled. Executable name: \"${ECL_NAME}\""
 fi
 echo "default lisp: $DEFAULTLISP"
 echo "wish executable name: \"${WISH}\""
 
+if test x"${chm}" = xtrue ; then
+  echo "CHM help files enabled"
+  echo "    HHC: \"${HHC}\""
+fi
+if test x"${xmaxima_exe}" = xtrue ; then
+   echo "Windows xmaxima.exe enabled"
+   echo "  GCC version GCCVER: ${GCCVER}"
+   echo "  TCLSTUBLIB: ${TCLSTUBLIB}"
+   if ! test -f "${TCLSTUBLIB}" ; then
+     AC_MSG_WARN(*** TCLSTUBLIB ${TCLSTUBLIB} not found)
+     xmaxima_exe_prerequisite=notfound
+   fi
+   echo "  TCLKITSH: ${TCLKITSH}"
+   if ! test -f "${TCLKITSH}" ; then
+     AC_MSG_WARN(*** TCLKITSH ${TCLKITSH} not found)
+     xmaxima_exe_prerequisite=notfound
+   fi
+   echo "  TCLKIT_RUNTIME: ${TCLKIT_RUNTIME}"
+   if ! test -f "${TCLKIT_RUNTIME}" ; then
+     AC_MSG_WARN(*** TCLKIT_RUNTIME ${TCLKIT_RUNTIME} not found)
+     xmaxima_exe_prerequisite=notfound
+   fi
+   echo "  SDXKIT: ${SDXKIT}"
+   if ! test -f "${SDXKIT}" ; then
+     AC_MSG_WARN(*** SDXKIT ${SDXKIT} not found)
+     xmaxima_exe_prerequisite=notfound
+   fi
+   echo "  IMGKIT: ${IMGKIT}"
+   if ! test -f "${IMGKIT}" ; then
+     AC_MSG_WARN(*** IMGKIT ${IMGKIT} not found)
+     xmaxima_exe_prerequisite=notfound
+   fi
+   if test x${xmaxima_exe_prerequisite} = xnotfound ; then
+     AC_MSG_WARN([A prerequisite for xmaxima.exe not found.  The missing components can be defined on the make command line.])
+   fi
+fi
