New upstream version 5.16.3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/macsys.lisp"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os win32 WIN32_TRUE WIN32_FALSE clisp_found cmucl_found scl_found sbcl_found acl_found gcl_found openmcl_found LANG_ES_TRUE LANG_ES_FALSE LANG_ES_UTF8_TRUE LANG_ES_UTF8_FALSE LANG_PT_TRUE LANG_PT_FALSE LANG_PT_UTF8_TRUE LANG_PT_UTF8_FALSE LANG_PT_BR_TRUE LANG_PT_BR_FALSE LANG_PT_BR_UTF8_TRUE LANG_PT_BR_UTF8_FALSE iconv_found recode_found USE_RECODE_TRUE USE_RECODE_FALSE CLISP_TRUE CLISP_FALSE GCL_TRUE GCL_FALSE CMUCL_TRUE CMUCL_FALSE SCL_TRUE SCL_FALSE SBCL_TRUE SBCL_FALSE ACL_TRUE ACL_FALSE OPENMCL_TRUE OPENMCL_FALSE GCL_ALT_LINK_TRUE GCL_ALT_LINK_FALSE CLISP_NAME CLISP_RUNTIME CLISP_RUNTIME_PATH CMUCL_NAME CMUCL_RUNTIME CMUCL_RUNTIME_PATH SCL_NAME SCL_RUNTIME SCL_RUNTIME_PATH SBCL_NAME GCL_NAME ACL_NAME OPENMCL_NAME DEFAULTLISP WISH POSIX_SHELL expanded_top_srcdir expanded_exec_prefix expanded_libdir expanded_libexecdir expanded_datadir expanded_infodir default_layout_autotools LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os win32 WIN32_TRUE WIN32_FALSE clisp_found cmucl_found scl_found sbcl_found acl_found gcl_found openmcl_found ecl_found LANG_ES_TRUE LANG_ES_FALSE LANG_ES_UTF8_TRUE LANG_ES_UTF8_FALSE LANG_PT_TRUE LANG_PT_FALSE LANG_PT_UTF8_TRUE LANG_PT_UTF8_FALSE LANG_PT_BR_TRUE LANG_PT_BR_FALSE LANG_PT_BR_UTF8_TRUE LANG_PT_BR_UTF8_FALSE iconv_found recode_found USE_RECODE_TRUE USE_RECODE_FALSE CLISP_TRUE CLISP_FALSE GCL_TRUE GCL_FALSE CMUCL_TRUE CMUCL_FALSE SCL_TRUE SCL_FALSE SBCL_TRUE SBCL_FALSE ACL_TRUE ACL_FALSE OPENMCL_TRUE OPENMCL_FALSE ECL_TRUE ECL_FALSE GCL_ALT_LINK_TRUE GCL_ALT_LINK_FALSE CLISP_NAME CLISP_RUNTIME CLISP_RUNTIME_PATH CMUCL_NAME CMUCL_RUNTIME CMUCL_RUNTIME_PATH SCL_NAME SCL_RUNTIME SCL_RUNTIME_PATH SBCL_NAME GCL_NAME ACL_NAME OPENMCL_NAME ECL_NAME DEFAULTLISP WISH POSIX_SHELL expanded_top_srcdir expanded_exec_prefix expanded_libdir expanded_libexecdir expanded_datadir expanded_infodir default_layout_autotools LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -799,6 +799,7 @@ Optional Features:
   --enable-acl                     Use ACL
   --enable-gcl                     Use GCL
   --enable-openmcl                 Use OpenMCL
+  --enable-ecl                 Use ECL
   --enable-lang-es                 Spanish language support
   --enable-lang-es-utf8            Spanish language support (UTF-8)
   --enable-lang-pt                 Portuguese language support
@@ -825,6 +826,7 @@ Optional Packages:
   --with-acl=<prog>                Use ACL executable <prog> (default lisp)
   --with-gcl=<prog>                Use GCL executable <prog> (default gcl)
   --with-openmcl=<prog>            Use OpenMCL executable <prog> (default openmcl)
+  --with-ecl=<prog>            Use ECL executable <prog> (default ecl)
   --with-default-lisp=<lisp>       Set default lisp implementation to <lisp>
   --with-posix-shell=</path/to/shell>    Use <shell> for maxima script (default /bin/sh)
   --with-wish=<prog>               Use <prog> for Tk wish shell (default wish)
@@ -1572,7 +1574,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=maxima
- VERSION=5.13.0
+ VERSION=5.16.3
 
 
 cat >>confdefs.h <<_ACEOF
@@ -2523,6 +2525,86 @@ echo "$as_me: WARNING: openmcl executable ${OPENMCL_NAME} not found in PATH" >&2
 	fi
 fi
 
+ecl_default_name=ecl
+# Check whether --enable-ecl or --disable-ecl was given.
+if test "${enable_ecl+set}" = set; then
+  enableval="$enable_ecl"
+  case "${enableval}" in
+       		yes) ecl=true
+		     explicit_lisp=true;;
+       		no)  ecl=false ;;
+		*) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-ecl" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-ecl" >&2;}
+   { (exit 1); exit 1; }; } ;;
+     	esac
+else
+  ecl=false
+fi;
+
+# Check whether --with-ecl or --without-ecl was given.
+if test "${with_ecl+set}" = set; then
+  withval="$with_ecl"
+  ecl=true
+	explicit_lisp=true
+	if test "$withval" = "yes"; then
+		ECL_NAME="${ecl}"
+	else
+		ECL_NAME="$withval"
+	fi
+else
+  ECL_NAME=${ecl_default_name}
+fi;
+if test x"${ecl}" = xtrue ; then
+	if test `echo "$ECL_NAME" | sed 's/\(.\).*/\1/'` = "/" ; then
+		if test -x "$ECL_NAME" ; then
+			ecl_found=true
+		else
+			ecl_found=false
+		fi
+	else
+		# Extract the first word of "$ECL_NAME", so it can be a program name with args.
+set dummy $ECL_NAME; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ecl_found+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ecl_found"; then
+  ac_cv_prog_ecl_found="$ecl_found" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ecl_found="true"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_ecl_found" && ac_cv_prog_ecl_found="false"
+fi
+fi
+ecl_found=$ac_cv_prog_ecl_found
+if test -n "$ecl_found"; then
+  echo "$as_me:$LINENO: result: $ecl_found" >&5
+echo "${ECHO_T}$ecl_found" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	fi
+	if test x"${ecl_found}" = xfalse ; then
+		{ echo "$as_me:$LINENO: WARNING: ecl executable ${ECL_NAME} not found in PATH" >&5
+echo "$as_me: WARNING: ecl executable ${ECL_NAME} not found in PATH" >&2;}
+	fi
+fi
+
 # Check whether --enable-lang-es or --disable-lang-es was given.
 if test "${enable_lang_es+set}" = set; then
   enableval="$enable_lang_es"
@@ -3037,6 +3119,42 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+	# Extract the first word of "$ECL_NAME", so it can be a program name with args.
+set dummy $ECL_NAME; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ecl_found+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ecl_found"; then
+  ac_cv_prog_ecl_found="$ecl_found" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ecl_found="true"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_ecl_found" && ac_cv_prog_ecl_found="false"
+fi
+fi
+ecl_found=$ac_cv_prog_ecl_found
+if test -n "$ecl_found"; then
+  echo "$as_me:$LINENO: result: $ecl_found" >&5
+echo "${ECHO_T}$ecl_found" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 
   	if test x"${clisp_found}" = xtrue ; then
   		clisp=true
@@ -3050,11 +3168,11 @@ fi
 	   	sbcl=true
 	elif test x"${acl_found}" = xtrue ; then
 		acl=true
-	elif test x"${openmcl_found}" = xtrue ; then
-		openmcl=true
+	elif test x"${ecl_found}" = xtrue ; then
+		ecl=true
 	else
-		{ { echo "$as_me:$LINENO: error: No lisp implementation specified and none of the default executables ${clisp_default_name}(clisp),${gcl_default_name}(GCL),${cmucl_default_name}(CMUCL),${scl_default_name}(SCL),${sbcl_default_name}(SBCL),${acl_default_name}(ACL),${openmcl_default_name}(OpenMCL) were found in PATH" >&5
-echo "$as_me: error: No lisp implementation specified and none of the default executables ${clisp_default_name}(clisp),${gcl_default_name}(GCL),${cmucl_default_name}(CMUCL),${scl_default_name}(SCL),${sbcl_default_name}(SBCL),${acl_default_name}(ACL),${openmcl_default_name}(OpenMCL) were found in PATH" >&2;}
+		{ { echo "$as_me:$LINENO: error: No lisp implementation specified and none of the default executables ${clisp_default_name}(clisp),${gcl_default_name}(GCL),${cmucl_default_name}(CMUCL),${scl_default_name}(SCL),${sbcl_default_name}(SBCL),${acl_default_name}(ACL),${openmcl_default_name}(OpenMCL),${ecl_default_name}(ECL) were found in PATH" >&5
+echo "$as_me: error: No lisp implementation specified and none of the default executables ${clisp_default_name}(clisp),${gcl_default_name}(GCL),${cmucl_default_name}(CMUCL),${scl_default_name}(SCL),${sbcl_default_name}(SBCL),${acl_default_name}(ACL),${openmcl_default_name}(OpenMCL),${ecl_default_name}(ECL) were found in PATH" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 fi
@@ -3127,6 +3245,16 @@ if test x$openmcl = xtrue; then
 else
   OPENMCL_TRUE='#'
   OPENMCL_FALSE=
+fi
+
+
+
+if test x$ecl = xtrue; then
+  ECL_TRUE=
+  ECL_FALSE='#'
+else
+  ECL_TRUE='#'
+  ECL_FALSE=
 fi
 
 
@@ -3227,7 +3355,7 @@ script the SCL executable is the program exec'd by that shell script." >&2;}
 fi
 
 if test x"${gcl}" = xtrue; then
-   result=`"${GCL_NAME}" -batch -eval '#+ansi-cl (format t "MAXIMA_GCL_ANSI_TEST_SUCCESS~%") #-ansi-cl (format t "MAXIMA_GCL_ANSI_TEST_FAILURE~%")' -eval '(quit)'`
+   result=`"${GCL_NAME}" -batch -eval '#+ansi-cl (format t "MAXIMA_GCL_ANSI_TEST_SUCCESS~%") #-ansi-cl (format t "MAXIMA_GCL_ANSI_TEST_FAILURE~%")' -eval '(bye)'`
    retval=$?
    if test ! x"${retval}" = x"0" ; then
       { { echo "$as_me:$LINENO: error: unable to run gcl executable \"${GCL_NAME}\"." >&5
@@ -3341,6 +3469,15 @@ echo "$as_me: error: openmcl not enabled" >&2;}
    { (exit 1); exit 1; }; }
 			fi
 			;;
+		ecl)
+			if test x"${ecl}" = xtrue ; then
+				DEFAULTLISP=ecl
+			else
+				{ { echo "$as_me:$LINENO: error: ecl not enabled" >&5
+echo "$as_me: error: ecl not enabled" >&2;}
+   { (exit 1); exit 1; }; }
+			fi
+			;;
 		*)
 			{ { echo "$as_me:$LINENO: error: Unknown argument ${DEFAULTLISP} to --with-default-lisp" >&5
 echo "$as_me: error: Unknown argument ${DEFAULTLISP} to --with-default-lisp" >&2;}
@@ -3362,12 +3499,15 @@ else
 		DEFAULTLISP=acl
 	elif test x"${openmcl}" = xtrue ; then
 		DEFAULTLISP=openmcl
+	elif test x"${ecl}" = xtrue ; then
+		DEFAULTLISP=ecl
 	else
 		{ { echo "$as_me:$LINENO: error: Internal error. No lisp enabled. Please contact maintainer." >&5
 echo "$as_me: error: Internal error. No lisp enabled. Please contact maintainer." >&2;}
    { (exit 1); exit 1; }; }
 	fi
 fi;
+
 
 
 
@@ -3463,7 +3603,7 @@ expanded_infodir="`eval \"prefix=${tmp_prefix};datarootdir=${datarootdir};echo $
 default_layout_autotools="true"
 
 
-                                                                                                                                                                                                                                                                                                                                                                                                                ac_config_files="$ac_config_files Makefile maxima-local xmaxima-local maxima.spec maxima.iss src/Makefile src/maxima src/maxima.bat src/rmaxima src/autoconf-variables.lisp lisp-utils/Makefile tests/Makefile doc/Makefile doc/emaxima/Makefile doc/info/Makefile doc/info/es/Makefile doc/info/es.utf8/Makefile doc/info/pt/Makefile doc/info/pt.utf8/Makefile doc/info/pt_BR/Makefile doc/info/pt_BR.utf8/Makefile doc/intromax/Makefile doc/man/Makefile doc/man/maxima.1 doc/share/Makefile interfaces/Makefile interfaces/emacs/Makefile interfaces/emacs/emaxima/Makefile interfaces/emacs/misc/Makefile interfaces/xmaxima/Makefile interfaces/xmaxima/autoconf-variables.tcl interfaces/xmaxima/Tkmaxima/Header.tcl interfaces/xmaxima/doc/Makefile interfaces/xmaxima/doc/figures/Makefile interfaces/xmaxima/msgs/Makefile interfaces/xmaxima/win32/Makefile plotting/mgnuplot share/Makefile demo/Makefile plotting/Makefile"
+                                                                                                                                                                                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile maxima-local xmaxima-local maxima.spec maxima.iss src/Makefile src/maxima src/maxima.bat src/rmaxima src/autoconf-variables.lisp lisp-utils/Makefile tests/Makefile doc/Makefile doc/emaxima/Makefile doc/info/Makefile doc/info/es/Makefile doc/info/es.utf8/Makefile doc/info/pt/Makefile doc/info/pt.utf8/Makefile doc/info/pt_BR/Makefile doc/info/pt_BR.utf8/Makefile doc/intromax/Makefile doc/man/Makefile doc/man/maxima.1 doc/man/ru/maxima.1 doc/share/Makefile interfaces/Makefile interfaces/emacs/Makefile interfaces/emacs/emaxima/Makefile interfaces/emacs/imaxima/Makefile interfaces/emacs/misc/Makefile interfaces/xmaxima/Makefile interfaces/xmaxima/autoconf-variables.tcl interfaces/xmaxima/Tkmaxima/Header.tcl interfaces/xmaxima/doc/Makefile interfaces/xmaxima/doc/figures/Makefile interfaces/xmaxima/msgs/Makefile interfaces/xmaxima/win32/Makefile plotting/mgnuplot share/Makefile demo/Makefile plotting/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3688,6 +3828,13 @@ if test -z "${OPENMCL_TRUE}" && test -z "${OPENMCL_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"OPENMCL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"OPENMCL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ECL_TRUE}" && test -z "${ECL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ECL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ECL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4151,10 +4298,12 @@ do
   "doc/intromax/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/intromax/Makefile" ;;
   "doc/man/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/man/Makefile" ;;
   "doc/man/maxima.1" ) CONFIG_FILES="$CONFIG_FILES doc/man/maxima.1" ;;
+  "doc/man/ru/maxima.1" ) CONFIG_FILES="$CONFIG_FILES doc/man/ru/maxima.1" ;;
   "doc/share/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/share/Makefile" ;;
   "interfaces/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/Makefile" ;;
   "interfaces/emacs/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/emacs/Makefile" ;;
   "interfaces/emacs/emaxima/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/emacs/emaxima/Makefile" ;;
+  "interfaces/emacs/imaxima/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/emacs/imaxima/Makefile" ;;
   "interfaces/emacs/misc/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/emacs/misc/Makefile" ;;
   "interfaces/xmaxima/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/Makefile" ;;
   "interfaces/xmaxima/autoconf-variables.tcl" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/autoconf-variables.tcl" ;;
@@ -4290,6 +4439,7 @@ s,@sbcl_found@,$sbcl_found,;t t
 s,@acl_found@,$acl_found,;t t
 s,@gcl_found@,$gcl_found,;t t
 s,@openmcl_found@,$openmcl_found,;t t
+s,@ecl_found@,$ecl_found,;t t
 s,@LANG_ES_TRUE@,$LANG_ES_TRUE,;t t
 s,@LANG_ES_FALSE@,$LANG_ES_FALSE,;t t
 s,@LANG_ES_UTF8_TRUE@,$LANG_ES_UTF8_TRUE,;t t
@@ -4320,6 +4470,8 @@ s,@ACL_TRUE@,$ACL_TRUE,;t t
 s,@ACL_FALSE@,$ACL_FALSE,;t t
 s,@OPENMCL_TRUE@,$OPENMCL_TRUE,;t t
 s,@OPENMCL_FALSE@,$OPENMCL_FALSE,;t t
+s,@ECL_TRUE@,$ECL_TRUE,;t t
+s,@ECL_FALSE@,$ECL_FALSE,;t t
 s,@GCL_ALT_LINK_TRUE@,$GCL_ALT_LINK_TRUE,;t t
 s,@GCL_ALT_LINK_FALSE@,$GCL_ALT_LINK_FALSE,;t t
 s,@CLISP_NAME@,$CLISP_NAME,;t t
@@ -4335,6 +4487,7 @@ s,@SBCL_NAME@,$SBCL_NAME,;t t
 s,@GCL_NAME@,$GCL_NAME,;t t
 s,@ACL_NAME@,$ACL_NAME,;t t
 s,@OPENMCL_NAME@,$OPENMCL_NAME,;t t
+s,@ECL_NAME@,$ECL_NAME,;t t
 s,@DEFAULTLISP@,$DEFAULTLISP,;t t
 s,@WISH@,$WISH,;t t
 s,@POSIX_SHELL@,$POSIX_SHELL,;t t
@@ -4647,6 +4800,9 @@ if test x"${acl}" = xtrue ; then
 fi
 if test x"${openmcl}" = xtrue ; then
 	echo "OpenMCL enabled. Executable name: \"${OPENMCL_NAME}\""
+fi
+if test x"${ecl}" = xtrue ; then
+	echo "ECL enabled. Executable name: \"${ECL_NAME}\""
 fi
 echo "default lisp: $DEFAULTLISP"
 echo "wish executable name: \"${WISH}\""
