New upstream version 5.12.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/macsys.lisp"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os win32 WIN32_TRUE WIN32_FALSE clisp_found cmucl_found scl_found sbcl_found acl_found gcl_found openmcl_found LANG_ES_TRUE LANG_ES_FALSE LANG_ES_UTF8_TRUE LANG_ES_UTF8_FALSE LANG_PT_TRUE LANG_PT_FALSE LANG_PT_UTF8_TRUE LANG_PT_UTF8_FALSE iconv_found recode_found USE_RECODE_TRUE USE_RECODE_FALSE CLISP_TRUE CLISP_FALSE GCL_TRUE GCL_FALSE CMUCL_TRUE CMUCL_FALSE SCL_TRUE SCL_FALSE SBCL_TRUE SBCL_FALSE ACL_TRUE ACL_FALSE OPENMCL_TRUE OPENMCL_FALSE GCL_ALT_LINK_TRUE GCL_ALT_LINK_FALSE CLISP_NAME CLISP_RUNTIME CLISP_RUNTIME_PATH CMUCL_NAME CMUCL_RUNTIME CMUCL_RUNTIME_PATH SCL_NAME SCL_RUNTIME SCL_RUNTIME_PATH SBCL_NAME GCL_NAME ACL_NAME OPENMCL_NAME DEFAULTLISP WISH POSIX_SHELL expanded_top_srcdir expanded_exec_prefix expanded_libdir expanded_libexecdir expanded_datadir expanded_infodir default_layout_autotools LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os win32 WIN32_TRUE WIN32_FALSE clisp_found cmucl_found scl_found sbcl_found acl_found gcl_found openmcl_found LANG_ES_TRUE LANG_ES_FALSE LANG_ES_UTF8_TRUE LANG_ES_UTF8_FALSE LANG_PT_TRUE LANG_PT_FALSE LANG_PT_UTF8_TRUE LANG_PT_UTF8_FALSE LANG_PT_BR_TRUE LANG_PT_BR_FALSE LANG_PT_BR_UTF8_TRUE LANG_PT_BR_UTF8_FALSE iconv_found recode_found USE_RECODE_TRUE USE_RECODE_FALSE CLISP_TRUE CLISP_FALSE GCL_TRUE GCL_FALSE CMUCL_TRUE CMUCL_FALSE SCL_TRUE SCL_FALSE SBCL_TRUE SBCL_FALSE ACL_TRUE ACL_FALSE OPENMCL_TRUE OPENMCL_FALSE GCL_ALT_LINK_TRUE GCL_ALT_LINK_FALSE CLISP_NAME CLISP_RUNTIME CLISP_RUNTIME_PATH CMUCL_NAME CMUCL_RUNTIME CMUCL_RUNTIME_PATH SCL_NAME SCL_RUNTIME SCL_RUNTIME_PATH SBCL_NAME GCL_NAME ACL_NAME OPENMCL_NAME DEFAULTLISP WISH POSIX_SHELL expanded_top_srcdir expanded_exec_prefix expanded_libdir expanded_libexecdir expanded_datadir expanded_infodir default_layout_autotools LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -803,6 +803,8 @@ Optional Features:
   --enable-lang-es-utf8            Spanish language support (UTF-8)
   --enable-lang-pt                 Portuguese language support
   --enable-lang-pt-utf8            Portuguese language support (UTF-8)
+  --enable-lang-pt_BR              Brazilian Portuguese language support
+  --enable-lang-pt_BR-utf8         Brazilian Portuguese language support (UTF-8)
   --enable-recode                  Use recode for charset conversion
   --enable-gcl-alt-link            Use GCL's alternate linking mechanism
 
@@ -1570,7 +1572,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=maxima
- VERSION=5.10.0
+ VERSION=5.12.0
 
 
 cat >>confdefs.h <<_ACEOF
@@ -2621,6 +2623,57 @@ else
 fi
 
 
+# Check whether --enable-lang-pt_BR or --disable-lang-pt_BR was given.
+if test "${enable_lang_pt_BR+set}" = set; then
+  enableval="$enable_lang_pt_BR"
+  case "${enableval}" in
+       		yes) lang_pt_br=true  ;;
+       		no)  lang_pt_br=false ;;
+		*) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-lang-pt_BR" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-lang-pt_BR" >&2;}
+   { (exit 1); exit 1; }; } ;;
+     	esac
+else
+  lang_pt_br=false
+fi;
+
+
+
+if test x$lang_pt_br = xtrue; then
+  LANG_PT_BR_TRUE=
+  LANG_PT_BR_FALSE='#'
+else
+  LANG_PT_BR_TRUE='#'
+  LANG_PT_BR_FALSE=
+fi
+
+
+# Check whether --enable-lang-pt_BR-utf8 or --disable-lang-pt_BR-utf8 was given.
+if test "${enable_lang_pt_BR_utf8+set}" = set; then
+  enableval="$enable_lang_pt_BR_utf8"
+  case "${enableval}" in
+       		yes) lang_pt_br_utf8=true  ;;
+       		no)  lang_pt_br_utf8=false ;;
+		*) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-lang-pt_BR-utf8" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-lang-pt_BR-utf8" >&2;}
+   { (exit 1); exit 1; }; } ;;
+     	esac
+else
+  lang_pt_br_utf8=false
+fi;
+
+
+
+if test x$lang_pt_br_utf8 = xtrue; then
+  LANG_PT_BR_UTF8_TRUE=
+  LANG_PT_BR_UTF8_FALSE='#'
+else
+  LANG_PT_BR_UTF8_TRUE='#'
+  LANG_PT_BR_UTF8_FALSE=
+fi
+
+
+
 # Check whether --enable-recode or --disable-recode was given.
 if test "${enable_recode+set}" = set; then
   enableval="$enable_recode"
@@ -3410,7 +3463,7 @@ expanded_infodir="`eval \"prefix=${tmp_prefix};echo ${infodir}\"`"
 default_layout_autotools="true"
 
 
-                                                                                                                                                                                                                                                                                                                                                                                            ac_config_files="$ac_config_files Makefile maxima-local xmaxima-local maxima.spec maxima.iss maxima-lang-es.iss maxima-lang-pt.iss src/Makefile src/maxima src/maxima.bat src/rmaxima src/autoconf-variables.lisp lisp-utils/Makefile tests/Makefile doc/Makefile doc/emaxima/Makefile doc/info/Makefile doc/info/es/Makefile doc/info/es.utf8/Makefile doc/info/pt/Makefile doc/info/pt.utf8/Makefile doc/intromax/Makefile doc/man/Makefile doc/man/maxima.1 doc/share/Makefile interfaces/Makefile interfaces/emacs/Makefile interfaces/emacs/emaxima/Makefile interfaces/emacs/misc/Makefile interfaces/xmaxima/Makefile interfaces/xmaxima/autoconf-variables.tcl interfaces/xmaxima/Tkmaxima/Header.tcl interfaces/xmaxima/msgs/Makefile interfaces/xmaxima/win32/Makefile plotting/mgnuplot share/Makefile demo/Makefile plotting/Makefile"
+                                                                                                                                                                                                                                                                                                                                                                                                                ac_config_files="$ac_config_files Makefile maxima-local xmaxima-local maxima.spec maxima.iss src/Makefile src/maxima src/maxima.bat src/rmaxima src/autoconf-variables.lisp lisp-utils/Makefile tests/Makefile doc/Makefile doc/emaxima/Makefile doc/info/Makefile doc/info/es/Makefile doc/info/es.utf8/Makefile doc/info/pt/Makefile doc/info/pt.utf8/Makefile doc/info/pt_BR/Makefile doc/info/pt_BR.utf8/Makefile doc/intromax/Makefile doc/man/Makefile doc/man/maxima.1 doc/share/Makefile interfaces/Makefile interfaces/emacs/Makefile interfaces/emacs/emaxima/Makefile interfaces/emacs/misc/Makefile interfaces/xmaxima/Makefile interfaces/xmaxima/autoconf-variables.tcl interfaces/xmaxima/Tkmaxima/Header.tcl interfaces/xmaxima/doc/Makefile interfaces/xmaxima/doc/figures/Makefile interfaces/xmaxima/msgs/Makefile interfaces/xmaxima/win32/Makefile plotting/mgnuplot share/Makefile demo/Makefile plotting/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3565,6 +3618,20 @@ if test -z "${LANG_PT_UTF8_TRUE}" && test -z "${LANG_PT_UTF8_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"LANG_PT_UTF8\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"LANG_PT_UTF8\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LANG_PT_BR_TRUE}" && test -z "${LANG_PT_BR_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LANG_PT_BR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LANG_PT_BR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LANG_PT_BR_UTF8_TRUE}" && test -z "${LANG_PT_BR_UTF8_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LANG_PT_BR_UTF8\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LANG_PT_BR_UTF8\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4065,8 +4132,6 @@ do
   "xmaxima-local" ) CONFIG_FILES="$CONFIG_FILES xmaxima-local" ;;
   "maxima.spec" ) CONFIG_FILES="$CONFIG_FILES maxima.spec" ;;
   "maxima.iss" ) CONFIG_FILES="$CONFIG_FILES maxima.iss" ;;
-  "maxima-lang-es.iss" ) CONFIG_FILES="$CONFIG_FILES maxima-lang-es.iss" ;;
-  "maxima-lang-pt.iss" ) CONFIG_FILES="$CONFIG_FILES maxima-lang-pt.iss" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/maxima" ) CONFIG_FILES="$CONFIG_FILES src/maxima" ;;
   "src/maxima.bat" ) CONFIG_FILES="$CONFIG_FILES src/maxima.bat" ;;
@@ -4081,6 +4146,8 @@ do
   "doc/info/es.utf8/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/info/es.utf8/Makefile" ;;
   "doc/info/pt/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/info/pt/Makefile" ;;
   "doc/info/pt.utf8/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/info/pt.utf8/Makefile" ;;
+  "doc/info/pt_BR/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/info/pt_BR/Makefile" ;;
+  "doc/info/pt_BR.utf8/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/info/pt_BR.utf8/Makefile" ;;
   "doc/intromax/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/intromax/Makefile" ;;
   "doc/man/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/man/Makefile" ;;
   "doc/man/maxima.1" ) CONFIG_FILES="$CONFIG_FILES doc/man/maxima.1" ;;
@@ -4092,6 +4159,8 @@ do
   "interfaces/xmaxima/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/Makefile" ;;
   "interfaces/xmaxima/autoconf-variables.tcl" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/autoconf-variables.tcl" ;;
   "interfaces/xmaxima/Tkmaxima/Header.tcl" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/Tkmaxima/Header.tcl" ;;
+  "interfaces/xmaxima/doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/doc/Makefile" ;;
+  "interfaces/xmaxima/doc/figures/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/doc/figures/Makefile" ;;
   "interfaces/xmaxima/msgs/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/msgs/Makefile" ;;
   "interfaces/xmaxima/win32/Makefile" ) CONFIG_FILES="$CONFIG_FILES interfaces/xmaxima/win32/Makefile" ;;
   "plotting/mgnuplot" ) CONFIG_FILES="$CONFIG_FILES plotting/mgnuplot" ;;
@@ -4229,6 +4298,10 @@ s,@LANG_PT_TRUE@,$LANG_PT_TRUE,;t t
 s,@LANG_PT_FALSE@,$LANG_PT_FALSE,;t t
 s,@LANG_PT_UTF8_TRUE@,$LANG_PT_UTF8_TRUE,;t t
 s,@LANG_PT_UTF8_FALSE@,$LANG_PT_UTF8_FALSE,;t t
+s,@LANG_PT_BR_TRUE@,$LANG_PT_BR_TRUE,;t t
+s,@LANG_PT_BR_FALSE@,$LANG_PT_BR_FALSE,;t t
+s,@LANG_PT_BR_UTF8_TRUE@,$LANG_PT_BR_UTF8_TRUE,;t t
+s,@LANG_PT_BR_UTF8_FALSE@,$LANG_PT_BR_UTF8_FALSE,;t t
 s,@iconv_found@,$iconv_found,;t t
 s,@recode_found@,$recode_found,;t t
 s,@USE_RECODE_TRUE@,$USE_RECODE_TRUE,;t t
diff --git a/doc/info/Makefile.am b/doc/info/Makefile.am
--- a/doc/info/Makefile.am
+++ b/doc/info/Makefile.am
@@ -14,7 +14,15 @@ if LANG_PT_UTF8
   PT_DIR_UTF8 = pt.utf8
 endif
 
-SUBDIRS = $(ES_DIR) $(ES_DIR_UTF8) $(PT_DIR) $(PT_DIR_UTF8)
+if LANG_PT_BR
+  PT_BR_DIR = pt_BR
+endif
+
+if LANG_PT_BR_UTF8
+  PT_BR_DIR_UTF8 = pt_BR.utf8
+endif
+
+SUBDIRS = $(ES_DIR) $(ES_DIR_UTF8) $(PT_DIR) $(PT_DIR_UTF8) $(PT_BR_DIR) $(PT_BR_DIR_UTF8)
 
 info_TEXINFOS = maxima.texi
 maxima_TEXINFOS = Introduction.texi Help.texi Command.texi Operators.texi \
@@ -23,16 +31,17 @@ maxima_TEXINFOS = Introduction.texi Help.texi Command.texi Operators.texi \
   Logarithms.texi Trigonometric.texi Special.texi \
   Limits.texi Differentiation.texi Integration.texi Equations.texi \
   Differential.texi Numerical.texi \
-  Statistics.texi Arrays.texi Matrices.texi Affine.texi Itensor.texi \
+  Arrays.texi Matrices.texi Affine.texi Itensor.texi \
   Ctensor.texi Atensor.texi Series.texi Number.texi Symmetries.texi \
   Groups.texi Runtime.texi Miscellaneous.texi Rules.texi Lists.texi \
   Function.texi Program.texi Debugging.texi Indices.texi Elliptic.texi \
   Bugs.texi nset.texi zeilberger.texi orthopoly.texi linearalgebra.texi \
   solve_rec.texi stringproc.texi numericalio.texi descriptive.texi \
-  distrib.texi simplex.texi simplifications.texi unit.texi makeOrders.texi \
+  distrib.texi draw.texi simplex.texi simplifications.texi unit.texi makeOrders.texi \
   mnewton.texi lsquares.texi plotdf.texi lindstedt.texi impdiff.texi \
-  ggf.texi f90.texi eval_string.texi diag.texi cholesky.texi dynamics.texi\
-  bode.texi augmented_lagrangian.texi opsubst.texi stirling.texi interpol.texi
+  ggf.texi f90.texi eval_string.texi diag.texi dynamics.texi\
+  bode.texi augmented_lagrangian.texi opsubst.texi stats.texi stirling.texi\
+  implicit_plot.texi interpol.texi lbfgs.texi romberg.texi grobner.texi
 
 figurefiles = \
 figures/dynamics1.gif\
@@ -43,6 +52,9 @@ figures/dynamics5.gif\
 figures/dynamics6.gif\
 figures/dynamics7.gif\
 figures/dynamics8.gif\
+figures/dynamics9.gif\
+figures/dynamics10.gif\
+figures/implicit_plot.gif\
 figures/plotdf1.gif\
 figures/plotdf2.gif\
 figures/plotdf3.gif\
@@ -76,34 +88,120 @@ figures/plotting24.gif\
 figures/plotting25.gif\
 figures/orthopoly1.gif
 
-maximahtml.mk:
-	perl ./texi2html -split_chapter --lang=en --output=. --css-include=./manual.css --init-file ./texi2html.init maxima.texi 
-	rm -f maximahtml.mk
-	ls -1 maxima*.html | sed 's/\(.*\)/MAXIMAHTML += \1/' > maximahtml.mk
+pdffigures = \
+figures/dynamics1.pdf\
+figures/dynamics2.pdf\
+figures/dynamics3.pdf\
+figures/dynamics4.pdf\
+figures/dynamics5.pdf\
+figures/dynamics6.pdf\
+figures/dynamics7.pdf\
+figures/dynamics8.pdf\
+figures/dynamics9.pdf\
+figures/dynamics10.pdf\
+figures/implicit_plot.pdf\
+figures/plotdf1.pdf\
+figures/plotdf2.pdf\
+figures/plotdf3.pdf\
+figures/plotdf4.pdf\
+figures/plotdf5.pdf\
+figures/plotdf6.pdf\
+figures/plotting1.pdf\
+figures/plotting2.pdf\
+figures/plotting3.pdf\
+figures/plotting4.pdf\
+figures/plotting5.pdf\
+figures/plotting6.pdf\
+figures/plotting7.pdf\
+figures/plotting8.pdf\
+figures/plotting9.pdf\
+figures/plotting10.pdf\
+figures/plotting11.pdf\
+figures/plotting12.pdf\
+figures/plotting13.pdf\
+figures/plotting14.pdf\
+figures/plotting15.pdf\
+figures/plotting16.pdf\
+figures/plotting17.pdf\
+figures/plotting18.pdf\
+figures/plotting19.pdf\
+figures/plotting20.pdf\
+figures/plotting21.pdf\
+figures/plotting22.pdf\
+figures/plotting23.pdf\
+figures/plotting24.pdf\
+figures/plotting25.pdf\
+figures/orthopoly1.pdf
 
-MAXIMAHTML = 
-include maximahtml.mk
+all-local: maxima-index.lisp maxima.html contents.hhc
 
-$(MAXIMAHTML): maxima.texi $(maxima_TEXINFOS)
+maxima-index.lisp: maxima.info build_index.pl
+	perl ./build_index.pl maxima.info ':crlf' > maxima-index.lisp
+
+maxima.html: maxima.texi $(maxima_TEXINFOS)
 	perl ./texi2html -split_chapter --lang=en --output=. --css-include=./manual.css --init-file ./texi2html.init maxima.texi 
+
+contents.hhc: maxima.html
 	perl ./create_index
 
 include $(top_srcdir)/common.mk
 genericdir = $(dochtmldir)
-genericdirDATA = \
-$(MAXIMAHTML)\
-$(figurefiles)\
-contents.hhc index.hhk header.hhp
+genericdirDATA = $(figurefiles) \
+contents.hhc index.hhk header.hhp maxima.hhp
+
+htmlname = maxima
+htmlinstdir = $(dochtmldir)
+include $(top_srcdir)/common-html.mk
+
+all-local: warn_texinfo
+dist-hook: check_texinfo
+
+install-data-local: install-maxima-index
+uninstall-local: uninstall-maxima-index
+
+install-maxima-index: maxima-index.lisp
+	test -z "$(infodir)" || mkdir -p -- "$(DESTDIR)$(infodir)"
+	$(INSTALL_DATA) maxima-index.lisp "$(DESTDIR)$(infodir)/maxima-index.lisp"
+
+uninstall-maxima-index: maxima-index.lisp
+	rm -f "$(DESTDIR)$(infodir)/maxima-index.lisp"
 
 clean-local: clean-info
 clean-local: clean-html
 
 clean-info:
 	rm -f maxima.info*
+	rm -f maxima-index.lisp
 
 clean-html:
 	rm -f maxima*.html
 	rm -f contents.hhc
 	rm -f index.hhk
 
-EXTRA_DIST = texi2html maximahtml.mk manual.css texi2html.init $(genericdirDATA) create_index header.hhp
+EXTRA_DIST = texi2html manual.css texi2html.init \
+    $(genericdirDATA) $(pdffigures) \
+    create_index maxima-index.lisp \
+    check_crlf check_tab fix_crlf fix_tab build_index.pl
+
+check_texinfo:
+	pattern=`printf "\r$$"` ; \
+	bad_files=`find . -name '*.texi' -print | xargs grep -l -e "$$pattern"` ; \
+	[ -z  "$$bad_files" ] || ( echo "ERROR: The following files have DOS-style EOLs: $$bad_files" ; \
+	echo "Run make distclean and then /doc/info/fix_crlf to fix the problem." ; exit 1 )
+	pattern=`printf "\t"` ; \
+	bad_files=`find . -name '*.texi' -print | xargs grep -l -e "$$pattern"` ; \
+	[ -z  "$$bad_files" ] || ( echo "ERROR: The following files have unexpanded Tabs: $$bad_files" ; \
+	echo "Run make distclean and then /doc/info/fix_tab to fix the problem." ; exit 1 )
+
+warn_texinfo:
+	pattern=`printf "\r$$"` ; \
+	bad_files=`find . -name '*.texi' -print | xargs grep -l -e "$$pattern"` ; \
+	[ -z  "$$bad_files" ] || ( echo "WARNING: The following files have DOS-style EOLs: $$bad_files" ; \
+	echo "Run /doc/info/fix_crlf to fix the problem." )
+	pattern=`printf "\t"` ; \
+	bad_files=`find . -name '*.texi' -print | xargs grep -l -e "$$pattern"` ; \
+	[ -z  "$$bad_files" ] || ( echo "WARNING: The following files have unexpanded Tabs: $$bad_files" ; \
+	echo "Run /doc/info/fix_tab to fix the problem." )
+
+.PHONY: check_texinfo warn_texinfo
+
